"""Public-safe regression guard for the stroke-merge detector calibration.

Locks rm_config.MERGE_JUMP_THRESHOLD / MERGE_PRESSURE_MIN (60 / 189) against
the NEUTRAL fixture corpus at tests/fixtures/render_neutral/ -- synthetic
shapes generated by tests/gen_neutral_fixtures.py, not real handwriting. This
is the public-tree companion to test_calibration.py (which stays private: it
is keyed to the author's own notebooks and cannot ship). See
tests/fixtures/render_neutral/NEUTRAL_PROVENANCE.md for the neutrality
statement.

Unlike test_calibration.py, this file does NOT import
tools/rm_calibrate_merge.py (not in the public MANIFEST -- see
tools/rm_build_public.py). It calls rm_render_page.detect_stroke_merge()
directly -- the one detector implementation the shipped tree actually has --
so this test's own dependency footprint is public-tree-clean.

Run: python -m pytest rm-mcp/tests/test_calibration_neutral.py
"""

from __future__ import annotations

import json
import sys
import unittest
from pathlib import Path

RM_MCP_DIR = Path(__file__).resolve().parent.parent
# Private layout: <repo>/tools beside <repo>/rm-mcp. Public layout is
# flattened by tools/rm_build_public.py: tools/ sits beside tests/.
TOOLS_DIR = next((d for d in (RM_MCP_DIR / "tools", RM_MCP_DIR.parent / "tools")
                  if (d / "rm_render_page.py").is_file()), RM_MCP_DIR / "tools")
for _p in (RM_MCP_DIR, TOOLS_DIR):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import rm_render_page as rp  # noqa: E402
from rm_config import MERGE_JUMP_THRESHOLD as DEFAULT_JUMP  # noqa: E402
from rm_config import MERGE_PRESSURE_MIN as DEFAULT_PRESSURE  # noqa: E402

FIXTURES = RM_MCP_DIR / "tests" / "fixtures" / "render_neutral"
LABELS = FIXTURES / "labels.json"


def _load_labels() -> dict:
    return json.loads(LABELS.read_text(encoding="utf-8"))


def _iter_labeled_pages():
    """Yield (fixture_path, page_no, rm_path, expected_dict) for every
    labeled page in the neutral corpus."""
    labels = _load_labels()
    for entry in labels["fixtures"]:
        fixture_dir = FIXTURES / entry["path"]
        for page_str, page_info in entry["pages"].items():
            rm_path = fixture_dir / entry["doc_uuid"] / f"{page_info['rm']}.rm"
            yield entry["path"], int(page_str), rm_path, page_info


class TestNeutralCorpusShape(unittest.TestCase):
    def test_labels_file_exists(self):
        self.assertTrue(LABELS.exists(), f"missing {LABELS}")

    def test_corpus_has_both_classes(self):
        pages = list(_iter_labeled_pages())
        artifact = sum(1 for _, _, _, exp in pages if exp["expected_has_artifact"])
        clean = sum(1 for _, _, _, exp in pages if not exp["expected_has_artifact"])
        self.assertGreaterEqual(artifact, 2, "need >=2 artifact fixture pages")
        self.assertGreaterEqual(clean, 2, "need >=2 clean fixture pages")


class TestDefaultThresholdsClassifyEveryPage(unittest.TestCase):
    """Re-parses every labeled .rm on disk and checks the shipping detector,
    run with the frozen default thresholds, reproduces the recorded label."""

    def test_every_page_matches_its_label(self):
        mismatches = []
        for path, page, rm_path, expected in _iter_labeled_pages():
            self.assertTrue(rm_path.exists(), f"missing fixture {rm_path}")
            blocks = rp.parse_rm_blocks(rm_path)
            got = rp.detect_stroke_merge(blocks, DEFAULT_JUMP, DEFAULT_PRESSURE)
            if got["has_artifact"] != expected["expected_has_artifact"]:
                mismatches.append(
                    f"{path} p{page}: got has_artifact={got['has_artifact']} "
                    f"expected {expected['expected_has_artifact']}")
            if got["severe_count"] != expected["expected_severe_count"]:
                mismatches.append(
                    f"{path} p{page}: got severe_count={got['severe_count']} "
                    f"expected {expected['expected_severe_count']}")
        self.assertFalse(mismatches, "calibration mismatch:\n  " + "\n  ".join(mismatches))

    def test_max_jump_matches_recorded_expectation(self):
        for path, page, rm_path, expected in _iter_labeled_pages():
            blocks = rp.parse_rm_blocks(rm_path)
            got = rp.detect_stroke_merge(blocks, DEFAULT_JUMP, DEFAULT_PRESSURE)
            self.assertAlmostEqual(
                got["max_jump"], expected["expected_max_jump_approx"], delta=0.5,
                msg=f"{path} p{page}: max_jump drifted from the recorded expectation "
                    "-- a parser bump or point-serialization change moved the "
                    "geometry this fixture pins.")


class TestDefaultSitsOffTheBoundary(unittest.TestCase):
    """The frozen default (60/189) must sit strictly between the clean and
    artifact classes in this corpus, with margin -- not merely separate them
    exactly at the boundary."""

    def test_default_sits_off_the_boundary(self):
        clean_max_jumps = []
        artifact_min_jumps = []
        for path, page, rm_path, expected in _iter_labeled_pages():
            blocks = rp.parse_rm_blocks(rm_path)
            got = rp.detect_stroke_merge(blocks, DEFAULT_JUMP, DEFAULT_PRESSURE)
            if expected["expected_has_artifact"]:
                artifact_min_jumps.append(got["max_jump"])
            else:
                clean_max_jumps.append(got["max_jump"])
        self.assertTrue(clean_max_jumps and artifact_min_jumps,
                         "need both classes present to compute a margin")
        clean_ceiling = max(clean_max_jumps)
        artifact_floor = min(artifact_min_jumps)
        self.assertLess(
            clean_ceiling, DEFAULT_JUMP,
            f"a clean fixture's max_jump ({clean_ceiling:.1f}) is not below "
            f"MERGE_JUMP_THRESHOLD ({DEFAULT_JUMP:g}) -- boundary collapsed.")
        self.assertGreater(
            artifact_floor, DEFAULT_JUMP,
            f"an artifact fixture's max_jump ({artifact_floor:.1f}) is not above "
            f"MERGE_JUMP_THRESHOLD ({DEFAULT_JUMP:g}) -- boundary collapsed.")
        margin = min(DEFAULT_JUMP - clean_ceiling, artifact_floor - DEFAULT_JUMP)
        self.assertGreater(margin, 0.0,
                           f"default margin {margin:.1f} collapsed onto the boundary")


if __name__ == "__main__":
    unittest.main()
