"""Public-safe golden-image regression test for the reMarkable render pipeline.

Locks the full render path -- rmscene parse -> rmscene->canvas transform
(PDF_RM_SCALE) -> PDF background raster (pypdfium2) -> PIL stroke overlay ->
supersample/downsample -> PNG -- against committed golden PNGs, one per
labeled page of the NEUTRAL fixture corpus (tests/fixtures/render_neutral/,
generated by tests/gen_neutral_fixtures.py; no personal content -- see
tests/fixtures/render_neutral/NEUTRAL_PROVENANCE.md).

This is the public-tree companion to test_render_goldens.py, which stays
private: its goldens are pages of Bradley's own handwriting and cannot ship
(tracked in the private backlog). The pipeline exercised here
is identical -- same RENDER_CLI, same tolerance model -- only the fixtures
differ.

Regenerate (only after an intended pipeline change, under the pins in
rm-mcp/requirements-pins.txt):
    python rm-mcp/tests/gen_neutral_fixtures.py
Review the PNG diff before committing -- an unexpected golden change is the
signal this test exists to raise.

Run: python -m pytest rm-mcp/tests/test_render_goldens_neutral.py
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

import numpy as np
from PIL import Image

RM_MCP_DIR = Path(__file__).resolve().parent.parent
if str(RM_MCP_DIR) not in sys.path:
    sys.path.insert(0, str(RM_MCP_DIR))
# Private layout: <repo>/tools beside <repo>/rm-mcp. Public layout (built by
# tools/rm_build_public.py) is flattened: tools/ sits beside tests/.
from _toolpath import tool_script  # noqa: E402
# The layout probe has to ask tool_script, not stat a flat path: since the S112
# split rm_render_page.py sits in tools/rm/ in the private tree, so the flat
# test failed for BOTH candidates and next() fell through to its default --
# picking rm-mcp/tools, a directory that does not exist at all.
TOOLS_DIR = next((d for d in (RM_MCP_DIR / "tools", RM_MCP_DIR.parent / "tools")
                  if tool_script(d, "rm_render_page.py").is_file()),
                 RM_MCP_DIR / "tools")
for _d in [TOOLS_DIR, TOOLS_DIR / "rm"]:
    if _d.is_dir() and str(_d) not in sys.path:
        sys.path.insert(0, str(_d))

FIXTURES = Path(__file__).resolve().parent / "fixtures" / "render_neutral"
LABELS = FIXTURES / "labels.json"
RENDER_CLI = tool_script(TOOLS_DIR, "rm_render_page.py")

GOLDEN_FLAGS = ["--supersample", "2"]
GOLDEN_SUFFIX = ".golden.png"
GOLDENS_SUBDIR = "_goldens"

# Same cross-machine tolerance model as the private suite: byte-identical on
# the mint machine, this band absorbs LANCZOS / library-build wobble
# elsewhere without letting a real geometry change through.
MEAN_ABS_TOL = 1.0
DIFF_FRAC_TOL = 0.001


def _load_labels() -> dict:
    return json.loads(LABELS.read_text(encoding="utf-8"))


def _render_fixture(fixture_dir: Path, out_dir: Path,
                    flags: list[str] = GOLDEN_FLAGS) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    proc = subprocess.run(
        [sys.executable, str(RENDER_CLI), str(fixture_dir),
         "--out", str(out_dir), *flags],
        capture_output=True, encoding="utf-8", errors="replace", timeout=600,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"render failed for {fixture_dir}:\n{proc.stdout}\n{proc.stderr}")


def _rendered_page_name(page: int) -> str:
    return f"page_{page:03d}.png"


def _golden_path(fixture_dir: Path, page: int) -> Path:
    return fixture_dir / GOLDENS_SUBDIR / f"page_{page:03d}{GOLDEN_SUFFIX}"


def _compare(rendered: Path, golden: Path) -> tuple[float, float, int]:
    ir = np.asarray(Image.open(rendered).convert("RGB"), dtype=np.int32)
    ig = np.asarray(Image.open(golden).convert("RGB"), dtype=np.int32)
    if ir.shape != ig.shape:
        return float("inf"), 1.0, 255
    d = np.abs(ir - ig)
    mean_abs = float(d.mean())
    diff_frac = float((d.sum(axis=2) > 0).mean())
    return mean_abs, diff_frac, int(d.max())


def _iter_fixture_pages():
    labels = _load_labels()
    for entry in labels["fixtures"]:
        fixture_dir = FIXTURES / entry["path"]
        for page_str in entry["pages"]:
            yield fixture_dir, entry["path"], int(page_str)


class TestGoldensExist(unittest.TestCase):
    def test_every_labeled_page_has_a_committed_golden(self):
        missing = [
            f"{path} page {page}"
            for fdir, path, page in _iter_fixture_pages()
            if not _golden_path(fdir, page).exists()
        ]
        self.assertFalse(
            missing,
            "no committed golden for: " + ", ".join(missing)
            + " -- run tests/gen_neutral_fixtures.py to mint them.")


class TestRenderMatchesGoldens(unittest.TestCase):
    """Re-render each fixture and diff every labeled page against its golden."""

    @classmethod
    def setUpClass(cls):
        cls._tmp = tempfile.mkdtemp(prefix="rm_goldens_neutral_")
        cls._rendered: dict[str, Path] = {}
        for entry in _load_labels()["fixtures"]:
            out = Path(cls._tmp) / entry["path"].replace("/", "_")
            _render_fixture(FIXTURES / entry["path"], out)
            cls._rendered[entry["path"]] = out

    @classmethod
    def tearDownClass(cls):
        tmp = getattr(cls, "_tmp", None)
        if tmp and Path(tmp).exists():
            shutil.rmtree(tmp, ignore_errors=True)

    def test_all_labeled_pages_within_tolerance(self):
        failures = []
        for fdir, path, page in _iter_fixture_pages():
            golden = _golden_path(fdir, page)
            rendered = self._rendered[path] / _rendered_page_name(page)
            self.assertTrue(golden.exists(), f"missing golden {golden}")
            self.assertTrue(rendered.exists(), f"missing render {rendered}")
            mean_abs, diff_frac, max_abs = _compare(rendered, golden)
            if mean_abs > MEAN_ABS_TOL or diff_frac > DIFF_FRAC_TOL:
                failures.append(
                    f"{path} p{page}: mean_abs={mean_abs:.4f} "
                    f"diff_frac={diff_frac:.5f} max_abs={max_abs} "
                    f"(tol mean<={MEAN_ABS_TOL} frac<{DIFF_FRAC_TOL})")
        self.assertFalse(failures, "golden mismatch:\n  " + "\n  ".join(failures))


class TestGoldenSensitivity(unittest.TestCase):
    """The golden must CATCH a real render change -- guards against a
    tolerance so loose it would pass anything. Renders the artifact fixture
    with thickened strokes and asserts the diff exceeds tolerance."""

    def test_thicker_strokes_exceed_tolerance(self):
        labels = _load_labels()
        artifact_entry = next(
            e for e in labels["fixtures"] if e["class"] == "artifact_native")
        fixture_dir = FIXTURES / artifact_entry["path"]
        page = int(next(iter(artifact_entry["pages"])))
        golden = _golden_path(fixture_dir, page)
        self.assertTrue(golden.exists(), f"missing golden {golden}")
        with tempfile.TemporaryDirectory() as td:
            out = Path(td)
            proc = subprocess.run(
                [sys.executable, str(RENDER_CLI), str(fixture_dir),
                 "--out", str(out), *GOLDEN_FLAGS, "--width-scale", "6.0"],
                capture_output=True, encoding="utf-8", errors="replace",
                timeout=600)
            self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
            rendered = out / _rendered_page_name(page)
            mean_abs, diff_frac, _ = _compare(rendered, golden)
            self.assertTrue(
                mean_abs > MEAN_ABS_TOL or diff_frac > DIFF_FRAC_TOL,
                f"perturbed render stayed within tolerance "
                f"(mean_abs={mean_abs:.4f} diff_frac={diff_frac:.5f}) -- "
                f"the golden band is too loose to catch a stroke-width change.")


if __name__ == "__main__":
    unittest.main()
